services:
  navidrome:
    image: ghcr.io/navidrome/navidrome:latest@sha256:2ae037d464de9f802d047165a13b1c9dc2bdbb14920a317ae4aef1233adc0a3c
    container_name: navidrome
    restart: unless-stopped
    user: "1000:1000"          # adjust if your 'media' UID/GID differ
    environment:
      ND_MUSICFOLDER: /music
      ND_DATAFOLDER: /data
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: "72h"
      ND_SCANSCHEDULE: "@every 15m"   # periodic rescan; can be empty for manual
      ND_LASTFM_APIKEY: ${ND_LASTFM_APIKEY}
      ND_LASTFM_SECRET: ${ND_LASTFM_SECRET}
      ND_ENABLETRANSCODINGCONFIG: "true"  # shows the Transcodings page in UI
      TZ: Asia/Dhaka
    volumes:
      - /data/media/music:/music:ro
      - /docker/music-stack/navidrome:/data
    ports:
      - "4533:4533"

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest@sha256:a6559012296a8d821e7fb397ac1c125f69b2cf4b1d3de996c1defda3287fdec6
    container_name: lidarr
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dhaka
    volumes:
      - /docker/music-stack/lidarr:/config
      - /data/media/music:/music
      - /data/downloads/qbittorrent:/downloads
    ports:
      - "8686:8686"

  lidify:
    image: thewicklowwolf/lidify:latest@sha256:958eaddeef8195470b974ee03512d9a5c31ad2af3167f7824448fb026fa9c94a
    container_name: lidify
    restart: unless-stopped
    user: "1000:1000"
    environment:
      last_fm_api_key: ${LIDIFY_LAST_FM_API_KEY}
      last_fm_api_secret: ${LIDIFY_LAST_FM_API_SECRET}
      mode: "LastFM"
      # optional (wire to Lidarr later if you want auto-adds)
      # lidarr_address: "http://lidarr:8686"
      # lidarr_api_key: "<LIDARR_API_KEY>"
      # root_folder_path: "/music/Library"
      # dry_run_adding_to_lidarr: "True"
    volumes:
      - /docker/music-stack/lidify:/lidify/config
    ports:
      - "5000:5000"
